# Generated by Django 4.2.9 on 2024-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advance_search',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
