# Generated by Django 4.2.9 on 2024-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_advance_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=False),
        ),
    ]
