# Generated by Django 4.2.9 on 2024-02-27 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_is_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
